/* eslint-disable global-require */
module.exports = {
  darkMode: "class",
  purge: ["./src/**/*.tsx", "./public/create.html"],
  theme: {
    backgroundColor: {
      canvas: "var(--color-bg-canvas)",
      "canvas-inverse": "var(--color-bg-canvas-inverse)",
      "canvas-inset": "var(--color-bg-canvas-inset)",
      primary: "var(--color-bg-primary)",
      secondary: "var(--color-bg-secondary)",
      tertiary: "var(--color-bg-tertiary)",
      overlay: "var(--color-bg-overlay)",
      backdrop: "var(--color-bg-backdrop)",
      info: "var(--color-bg-info)",
      danger: "var(--color-bg-danger)",
      success: "var(--color-bg-success)",
      warning: "var(--color-bg-warning)",
      "info-inverse": "var(--color-bg-info-inverse)",
      "danger-inverse": "var(--color-bg-danger-inverse)",
      "success-inverse": "var(--color-bg-success-inverse)",
      "warning-inverse": "var(--color-bg-warning-inverse)",
      button: {
        DEFAULT: "var(--color-btn-bg)",
        primary: "var(--color-btn-primary-bg)",
        "primary-disabled": "var(--color-btn-primary-disabled-bg)",
        "danger-disabled": "var(--color-btn-danger-disabled-bg)",
      },
    },
    borderColor: {
      primary: "var(--color-border-primary)",
      secondary: "var(--color-border-secondary)",
      tertiary: "var(--color-border-tertiary)",
      overlay: "var(--color-border-overlay)",
      inverse: "var(--color-border-inverse)",
      info: "var(--color-border-info)",
      danger: "var(--color-border-danger)",
      success: "var(--color-border-success)",
      warning: "var(--color-border-warning)",
      button: {
        DEFAULT: "var(--color-btn-border)",
        primary: "var(--color-btn-primary-border)",
        "primary-disabled": "var(--color-btn-primary-disabled-border)",
        "danger-disabled": "var(--color-border-danger)",
      },
    },
    textColor: (theme) => ({
      ...theme("colors"),
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      tertiary: "var(--color-text-tertiary)",
      placeholder: "var(--color-text-placeholder)",
      disabled: "var(--color-text-disabled)",
      inverse: "var(--color-text-inverse)",
      link: "var(--color-text-link)",
      danger: "var(--color-text-danger)",
      success: "var(--color-text-success)",
      warning: "var(--color-text-warning)",
      white: "var(--color-text-white)",
      button: {
        DEFAULT: "var(--color-btn-text)",
        primary: "var(--color-btn-primary-text)",
        outline: "var(--color-btn-outline-text)",
        danger: "var(--color-btn-danger-text)",
        "primary-disabled": "var(--color-btn-primary-disabled-text)",
        "outline-disabled": "var(--color-btn-outline-disabled-text)",
        "danger-disabled": "var(--color-btn-danger-disabled-text)",
      },
      input: {},
    }),
    placeholder: (theme) => theme("textColor"),
    colors: {
      transparent: "transparent",
      gray: {
        0: "var(--color-scale-gray-0)",
        100: "var(--color-scale-gray-1)",
        200: "var(--color-scale-gray-2)",
        300: "var(--color-scale-gray-3)",
        400: "var(--color-scale-gray-4)",
        500: "var(--color-scale-gray-5)",
        600: "var(--color-scale-gray-6)",
        700: "var(--color-scale-gray-7)",
        800: "var(--color-scale-gray-8)",
        900: "var(--color-scale-gray-9)",
      },
      blue: {
        0: "var(--color-scale-blue-0)",
        100: "var(--color-scale-blue-1)",
        200: "var(--color-scale-blue-2)",
        300: "var(--color-scale-blue-3)",
        400: "var(--color-scale-blue-4)",
        500: "var(--color-scale-blue-5)",
        600: "var(--color-scale-blue-6)",
        700: "var(--color-scale-blue-7)",
        800: "var(--color-scale-blue-8)",
        900: "var(--color-scale-blue-9)",
      },
      green: {
        0: "var(--color-scale-green-0)",
        100: "var(--color-scale-green-1)",
        200: "var(--color-scale-green-2)",
        300: "var(--color-scale-green-3)",
        400: "var(--color-scale-green-4)",
        500: "var(--color-scale-green-5)",
        600: "var(--color-scale-green-6)",
        700: "var(--color-scale-green-7)",
        800: "var(--color-scale-green-8)",
        900: "var(--color-scale-green-9)",
      },
      yellow: {
        0: "var(--color-scale-yellow-0)",
        100: "var(--color-scale-yellow-1)",
        200: "var(--color-scale-yellow-2)",
        300: "var(--color-scale-yellow-3)",
        400: "var(--color-scale-yellow-4)",
        500: "var(--color-scale-yellow-5)",
        600: "var(--color-scale-yellow-6)",
        700: "var(--color-scale-yellow-7)",
        800: "var(--color-scale-yellow-8)",
        900: "var(--color-scale-yellow-9)",
      },
      purple: {
        0: "var(--color-scale-purple-0)",
        100: "var(--color-scale-purple-1)",
        200: "var(--color-scale-purple-2)",
        300: "var(--color-scale-purple-3)",
        400: "var(--color-scale-purple-4)",
        500: "var(--color-scale-purple-5)",
        600: "var(--color-scale-purple-6)",
        700: "var(--color-scale-purple-7)",
        800: "var(--color-scale-purple-8)",
        900: "var(--color-scale-purple-9)",
      },
      orange: {
        0: "var(--color-scale-orange-0)",
        100: "var(--color-scale-orange-1)",
        200: "var(--color-scale-orange-2)",
        300: "var(--color-scale-orange-3)",
        400: "var(--color-scale-orange-4)",
        500: "var(--color-scale-orange-5)",
        600: "var(--color-scale-orange-6)",
        700: "var(--color-scale-orange-7)",
        800: "var(--color-scale-orange-8)",
        900: "var(--color-scale-orange-9)",
      },
      red: {
        0: "var(--color-scale-red-0)",
        100: "var(--color-scale-red-1)",
        200: "var(--color-scale-red-2)",
        300: "var(--color-scale-red-3)",
        400: "var(--color-scale-red-4)",
        500: "var(--color-scale-red-5)",
        600: "var(--color-scale-red-6)",
        700: "var(--color-scale-red-7)",
        800: "var(--color-scale-red-8)",
        900: "var(--color-scale-red-9)",
      },
      pink: {
        0: "var(--color-scale-pink-0)",
        100: "var(--color-scale-pink-1)",
        200: "var(--color-scale-pink-2)",
        300: "var(--color-scale-pink-3)",
        400: "var(--color-scale-pink-4)",
        500: "var(--color-scale-pink-5)",
        600: "var(--color-scale-pink-6)",
        700: "var(--color-scale-pink-7)",
        800: "var(--color-scale-pink-8)",
        900: "var(--color-scale-pink-9)",
      },
    },
    fontFamily: {
      sans: [
        "Inter",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      // mono: ["Menlo", "Monaco", "Courier New", "monospace"],
    },
    fontSize: {
      l: "var(--font-h00)",
      0: "var(--font-h0)",
      1: "var(--font-h1)",
      2: "var(--font-h2)",
      3: "var(--font-h3)",
      4: "var(--font-h4)",
      5: "var(--font-h5)",
      6: "var(--font-h6)",
    },
    spacing: {
      0: "0",
      1: "4px",
      2: "8px",
      3: "16px",
      4: "24px",
      5: "32px",
      6: "40px",
      7: "48px",
      8: "64px",
      9: "80px",
      10: "96px",
      11: "112px",
      12: "128px",
    },
    letterSpacing: {
      DEFAULT: "0",
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
    },
    extend: {
      lineHeight: {
        100: "100%",
        125: "125%",
        150: "150%",
      },
    },
    screens: {
      sm: "544px",
      md: "768px",
      lg: "1012px",
      xl: "1280px",
    },
  },
  variants: {
    backgroundColor: ["responsive", "hover", "group-hover"],
    scrollbar: ["rounded", "dark"],
  },
  plugins: [require("tailwind-scrollbar")],
};
