export enum AuthenticationStatusEnum {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_SIGNUP_SUCCESSFUL = "USER_SIGNUP_SUCCESSFUL",
    CREDENTIALS_INCORRECT = "CREDENTIALS_INCORRECT",
    USER_UNREGISTERED = "USER_UNREGISTERED",
}
